from enum import Enum, auto

class NAKU_Events(Enum):
    RADIO_RECEIVED = auto()
    RADIO_TRANSMITED = auto()
    RADIO_RX_TIMEOUT = auto()
    RADIO_TX_TIMEOUT = auto()
    PRINTED = auto()
    SCRIPT_STARTED = auto()
    SCRIPT_FINISHED = auto()
    SESSION_STARTED = auto()
    SESSION_ABORTED = auto()
    SESSION_FINISHED = auto()
    PAUSED = auto()
    RUNTIME_ERROR = auto()
    ROTATOR_TURNED_AWAY = auto()
    ROTATOR_CRITICAL_ERROR = auto()
    ROTATOR_AIMED = auto()
    ROTATE_EVENT = auto()


class NAKU_Methods(Enum):
    GET_STATION_LABEL = auto()
    GET_SAT_NAME = auto()

    RADIO_MODULATION = auto()
    RADIO_HEADER_MODE = auto()
    RADIO_CODING_RATE = auto()
    RADIO_BANDWIDTH = auto()
    RADIO_SPREADING_FACTOR = auto()
    RADIO_CRC_MODE = auto()
    RADIO_TX_POWER = auto()
    RADIO_SYNC_WORD = auto()
    RADIO_PREAMBLE_LENGTH = auto()
    RADIO_PAYLOAD_LENGTH = auto()
    RADIO_AUTO_GAIN_CONTROL = auto()
    RADIO_LOW_NOIZE_AMPLIFIER = auto()
    RADIO_FREQUENCY = auto()
    RADIO_LOW_DATA_RATE_OPTIMIZE = auto()

    RADIO_GET_RX_TX_FIFO_BASE_ADDR = auto()
    RADIO_READ_CONFIG = auto()

    RADIO_SEND = auto()
    RADIO_SEND_REPEAT = auto()
    RADIO_WAIT_RX = auto()
    RADIO_INIT = auto()
    CLEAR_RX_BUFFER = auto()
    CLEAR_TX_BUFFER = auto()
    SET_RX_TIMEOUT = auto()
    GET_RX_BUFFER = auto()
    GET_TX_BUFFER = auto()

    SET_POSITION = auto()
    GET_POSITION = auto()
    GET_POSITION_ERROR = auto()

    GET_REMAINING_SESSION_TIME = auto()
    START_SESSION = auto()
    RUN_SCRIPT = auto()
    RUN_SCRIPT_PATH = auto()
    PAUSE_EXECUTOR = auto()
    NEXT_STEP = auto()
    TERMINATE_SCRIPT = auto()
    ABORT_SESSION = auto()
    CONTINUE_EXECUTOR = auto()
    GO_INTO = auto()
    GO_OUT = auto()
    HELP = auto()
    ECHO = auto()
    CONNECT = auto()